<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3185" started-at="2020-03-06T14:38:35 IST" finished-at="2020-03-06T14:38:38 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3185" started-at="2020-03-06T14:38:35 IST" finished-at="2020-03-06T14:38:38 IST">
      <class name="extentreport.report">
        <test-method status="PASS" signature="startReport1()[pri:0, instance:extentreport.report@534df152]" name="startReport1" is-config="true" duration-ms="1388" started-at="2020-03-06T14:38:35 IST" finished-at="2020-03-06T14:38:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport1 -->
        <test-method status="PASS" signature="demoReportPass()[pri:0, instance:extentreport.report@534df152]" name="demoReportPass" duration-ms="29" started-at="2020-03-06T14:38:36 IST" finished-at="2020-03-06T14:38:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoReportPass -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extentreport.report@534df152]" name="getResult" is-config="true" duration-ms="15" started-at="2020-03-06T14:38:36 IST" finished-at="2020-03-06T14:38:36 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoReportPass status=SUCCESS method=report.demoReportPass()[pri:0, instance:extentreport.report@534df152] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="demoReportfail()[pri:0, instance:extentreport.report@534df152]" name="demoReportfail" duration-ms="8" started-at="2020-03-06T14:38:36 IST" finished-at="2020-03-06T14:38:36 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at extentreport.report.demoReportfail(report.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoReportfail -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extentreport.report@534df152]" name="getResult" is-config="true" duration-ms="2" started-at="2020-03-06T14:38:36 IST" finished-at="2020-03-06T14:38:36 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoReportfail status=FAILURE method=report.demoReportfail()[pri:0, instance:extentreport.report@534df152] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:extentreport.report@534df152]" name="endReport" is-config="true" duration-ms="1527" started-at="2020-03-06T14:38:36 IST" finished-at="2020-03-06T14:38:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- extentreport.report -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
